<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.gold.ordance</groupId>
    <artifactId>rgo-wm-dependencies</artifactId>
    <version>24.0.0-SNAPSHOT</version>

    <packaging>pom</packaging>

    <properties>
        <common-dependencies-bom.version>24.0.0-SNAPSHOT</common-dependencies-bom.version>
        <rgo-wm-common-test-utils.version>24.0.0-SNAPSHOT</rgo-wm-common-test-utils.version>
        <rgo-wm-common-utils-bom.version>24.0.0-SNAPSHOT</rgo-wm-common-utils-bom.version>
        <rgo-wm-spring-bom.version>24.0.0-SNAPSHOT</rgo-wm-spring-bom.version>
        <rgo-wm-spring-autoconfig-bom.version>24.0.0-SNAPSHOT</rgo-wm-spring-autoconfig-bom.version>
        <spring-boot.version>3.4.3</spring-boot.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- rgo-wm modules -->
            <dependency>
                <groupId>ru.gold.ordance</groupId>
                <artifactId>common-dependencies-bom</artifactId>
                <version>${common-dependencies-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>ru.gold.ordance</groupId>
                <artifactId>rgo-wm-common-test-utils-random</artifactId>
                <version>${rgo-wm-common-test-utils.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>ru.gold.ordance</groupId>
                <artifactId>rgo-wm-common-utils-bom</artifactId>
                <version>${rgo-wm-common-utils-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>ru.gold.ordance</groupId>
                <artifactId>rgo-wm-spring-bom</artifactId>
                <version>${rgo-wm-spring-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>ru.gold.ordance</groupId>
                <artifactId>rgo-wm-spring-autoconfig-bom</artifactId>
                <version>${rgo-wm-spring-autoconfig-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- /rgo-wm modules -->

            <!-- spring-boot -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- /spring-boot -->
        </dependencies>
    </dependencyManagement>
</project>